baseURL = "/"
languageCode = "en-uk"
title = "Denys Kolesnyk"
theme = "hugo-ivy"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "â†©"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 3
  [[menu.main]]
    name = "Media"
    url = "/media/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "mailto:dkolesnyk@pm.me"
    weight = 5

[params]
  description = "Geopolitical and Information Risk Consultant"
  footer = "&copy; Denys Kolesnyk 2019-{Year}"
  highlightjsLang = ["latex"]
  highlightjsTheme = "github"
  highlightjsVersion = "11.7.0"
  favicon = "favicon.ico"

[markup]
  [markup.highlight]
    codeFences = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true